### ISSUE TITLE
unusable

### ISSUE THREAD

**Issue by tilgwullfi** [matteo-convertino/otpmanager-nextcloud#10]
The web application loads indefinitely after the last update.

The android mobile app asks for authentication (which password does it expect?!) after access already has been granted to the account.
This already was the case before the nextcloud app update. The app tells me to: "Please update the extension on the server to version 1.0.0 or higher." > which extension?

Nice, now I can't access the OTP codes.

OTP Manager version: 0.3.0
Android App version: 1.3.0.14

**Comment by tilgwullfi** [comment]
okay, after looking for errors in the log and a reboot, the web app actually prompts me to input a password, which I suspect would be the password the app asks me for

bottom line: a reboot did the job, but clearer error messages would be useful

**Comment by matteo-convertino** [comment]
HI,
Sorry if you encountered any difficulties after updating to the new version. I hope you haven't lost any accounts and that everything is resolved now.
Soon I will publish a release where I will be more clear with the error messages. Thanks for the feedback.

**Comment by felsss** [comment]
Hello,
I have exactly the same issue after updating web app to 0.3.0.
I tried to uninstall the app, remove tables in database related to otpmanager, and entries in migration tables, reinstalled the app, but still the same. The web app is stuck in loading, and the android app (which seems to handle correctly a subdir in the URL now) asks for a password, but I've never set a password in the web app before updating it to 0.3.0.

**Comment by matteo-convertino** [comment]
The password is something added with version 0.3.0, in fact a form should appear for creating that password. However, it seems that another user has opened another issuer (#11) on the same problem. It would be best to continue the discussion there.
